spring:
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: main_route
          uri: lb://kp-main
          predicates:
            - Path=/main/**
          filters:
            - RewritePath=/main/(?<segment>.*),/$\{segment}
  main:
    web-application-type: reactive
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
  application:
    name: kp-gateway

server:
  port: 88