spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/know_pub?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: kp-other
server:
  port: 8089